name: Telegram Auto Post

on:
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 7 * * *'
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram Message
        run: |
          MESSAGE="👋 Community Note

If you haven't registered an exchange account yet, you can use my referral links below to get started.

Binance TH:
https://accounts.binance.th/th/register?ref=BTCCSxBNTH1

Bitget:
https://partner.bitget.com/bg/56GKTB

Bybit:
https://partner.bybit.com/b/115799

MEXC:
https://www.mexc.com/acquisition/custom-sign-up?shareCode=mexc-1N9Xt

No leverage.
No futures.
Survival first, profit second.

— BTC_Chopsticks"

          curl -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.CHAT_ID }}" \
          --data-urlencode text="$MESSAGE"
